### ISSUE TITLE
Spoofchecker is not loading in roundcubemail-docker

### ISSUE THREAD

**Issue by GrahamCobb** [roundcube/roundcubemail-docker#167]
I have just tried to create a new roundcube deployment using roundcubemail-docker (roundcube/roundcubemail:latest-fpm). As soon as I look at any email, it fails with errors about Spoofchecker.

I haven't included the errors here because this is a known issue: https://github.com/roundcube/roundcubemail/issues/8127#issuecomment-877759873-permalink

How has a release of roundcubemail-docker happened which does not run at all? More usefully, how do I work round it - is there something I can change in the config files?

**Comment by GrahamCobb** [comment]
Hmm... It looks like it isn't quite the same issue.  intl is installed - I can find it in the container filesystem and phpinfo confirms it is loaded.

The actual exception is:

```
/plugins/zipdownload/zipdownload.php on line 405PHP message: PHP Fatal error:  Uncaught Error: Class "Spoofchecker" not found in /var/www/html/site/roundcube/program/lib/Roundcube/rcube_spoofchecker.php:50
Stack trace:
#0 /var/www/html/site/roundcube/program/actions/mail/index.php(1400): rcube_spoofchecker::check('verifier.port25...')
#1 /var/www/html/site/roundcube/program/actions/mail/index.php(523): rcmail_action_mail_index::address_string('auth-results@ve...', 3, false, NULL, NULL)
#2 /var/www/html/site/roundcube/program/actions/mail/list.php(123): rcmail_action_mail_index::js_message_list(Array, false, Array)
#3 /var/www/html/site/roundcube/program/include/rcmail.php(275): rcmail_action_mail_list->run(Array)
#4 /var/www/html/site/roundcube/index.php(283): rcmail->action_handler()
#5 {main}
  thrown in /var/www/html/site/roundcube/program/lib/Roundcube/rcube_spoofchecker.php on line 50" while reading response header from upstream, client: 172.26.0.3, server: REDACTED, request: "GET /roundcube/?_task=mail&_action=list&_refresh=1&_layout=widescreen&_mbox=INBOX&_page=&_remote=1&_unlock=loading1642713152200&_=1642713151800 HTTP/1.1", upstream: "fastcgi://172.28.0.5:9000", host: "REDACTED", referrer: "REDACTED"
```

**Comment by GrahamCobb** [comment]
I don't know what I had messed up but it is all working now. Sorry for the noise.
